kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "manual"
  selector:
    matchLabels:
      name: example-pv
